-- V1__init.sql
-- Initial schema for ecommerce database.
-- Generated from SQL/initial.sql on 2026-04-07.

create table customer(
	customer_id int generated by default as identity,
	first_name varchar(100),
	last_name varchar(100),
	email varchar(100) unique,
	password varchar(100),
	phone_number varchar(100),
	email_verified boolean NOT NULL DEFAULT FALSE,
	created_at timestamp NOT null DEFAULT now(),
	updated_at timestamp NOT null DEFAULT now(),

	primary key (customer_id)
);

CREATE TABLE verification_token(
	verification_token_id int generated by default as identity,
	token varchar(255),
	created_timestamp timestamp NOT NULL DEFAULT now(),
	customer_id int NOT NULL references customer(customer_id),

	PRIMARY KEY (verification_token_id)
);

create table address(
	address_id int generated by default as identity,
	full_name varchar(255),
	phone_number varchar(20),
	street varchar(255),
	city varchar(255),
	state varchar(100),
	country varchar(100),
	postal_code varchar(20),
	is_default boolean NOT null default false,
	customer_id int references customer(customer_id),

	primary key (address_id)
);

create table category(
	category_id int generated by default as identity,
	name varchar(100),
	description varchar(255),

	primary key (category_id)
);

create table product(
	product_id int generated by default as identity,
	name varchar(255),
	brand varchar(100),
	model varchar(100),
	description varchar(255),
	created_at timestamp NOT null DEFAULT now(),
	updated_at timestamp NOT null DEFAULT now(),
	category_id int references category(category_id),

	primary key (product_id)
);

create table product_variant(
	product_variant_id int generated by default as identity,
	sku varchar(100) not null unique,
	price numeric(10,2),
	color varchar(50),
	stock_quantity int,
	warranty_months int,
	attributes JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(attributes) = 'object'),
	product_id int references product(product_id),

	primary key (product_variant_id)
);

create table cart(
	cart_id int generated by default as identity,
	created_at timestamp NOT null DEFAULT now(),
	updated_at timestamp NOT null DEFAULT now(),
	status varchar(50),
	customer_id int references customer(customer_id),

	primary key (cart_id)
);

create table cart_item(
	cart_id int references cart(cart_id),
	product_variant_id int references product_variant(product_variant_id),
	quantity int,
	added_at timestamp NOT null DEFAULT now(),

	primary key (cart_id, product_variant_id)
);

create table wishlist(
	wishlist_id int generated by default as identity,
	customer_id int references customer(customer_id),
	name varchar(100),
	created_at timestamp NOT null DEFAULT now(),
	updated_at timestamp not null default now(),

	primary key (wishlist_id)
);

create table wishlist_item(
	wishlist_id int references wishlist(wishlist_id),
	product_variant_id int references product_variant(product_variant_id),
	added_at timestamp NOT null DEFAULT now(),

	primary key (wishlist_id, product_variant_id)
);

create table order_status(
	status_id int generated by default as identity,
	status_code varchar(50),
	description varchar(255),

	primary key (status_id)
);

create table orders(
	order_id int generated by default as identity,
	order_date timestamp DEFAULT now(),
	total_price numeric(10,2),
	created_at timestamp NOT null DEFAULT now(),
	updated_at timestamp NOT null DEFAULT now(),
	status_id int references order_status(status_id),
	shipping_address_id int references address(address_id),
	customer_id int references customer(customer_id),

	primary key(order_id)
);

create table order_item(
	order_id int references orders(order_id),
	product_variant_id int references product_variant(product_variant_id),
	quantity int,
	unit_price numeric(10,2),
	discount numeric(10,2),

	primary key (order_id, product_variant_id)
);

create table order_status_history(
	history_id int generated by default as identity,
	changed_at timestamp NOT null DEFAULT now(),
	changed_by varchar(100),
	note varchar(255),
	order_id int references orders(order_id),
	status_id int references order_status(status_id),

	primary key (history_id)
);

create table payment_method(
	method_id int generated by default as identity,
	method_name varchar(100),
	description varchar(255),

	primary key (method_id)
);

create table payment (
	payment_id int generated by default as identity,
	payment_date timestamp NOT null DEFAULT now(),
	amount numeric(10,2),
	status varchar(50),
	transaction_id varchar(255),
	method_id int references payment_method(method_id),
	order_id int unique references orders(order_id),

	primary key(payment_id)
);

create table shipment(
	shipment_id int generated by default as identity,
	carrier varchar(100),
	tracking_number varchar(100),
	shipment_date timestamp,
	delivered_date timestamp,
	status varchar(50),
	shipping_address_id int references address(address_id),
	order_id int unique references orders(order_id),

	primary key(shipment_id)
);
