-- V2__add_rbac.sql
-- Add Role-Based Access Control tables and seed data.
-- Roles: CUSTOMER (default for all users), ADMIN (platform operators).

-- Role table
CREATE TABLE role (
    role_id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) NOT NULL UNIQUE,

    PRIMARY KEY (role_id)
);

-- Many-to-many join table: customer <-> role
CREATE TABLE customer_role (
    customer_id INT NOT NULL REFERENCES customer(customer_id),
    role_id INT NOT NULL REFERENCES role(role_id),

    PRIMARY KEY (customer_id, role_id)
);

-- Seed roles
INSERT INTO role (name) VALUES ('CUSTOMER');
INSERT INTO role (name) VALUES ('ADMIN');

-- Assign CUSTOMER role to all existing customers
INSERT INTO customer_role (customer_id, role_id)
SELECT c.customer_id, r.role_id
FROM customer c, role r
WHERE r.name = 'CUSTOMER'
  AND NOT EXISTS (
    SELECT 1 FROM customer_role cr
    WHERE cr.customer_id = c.customer_id AND cr.role_id = r.role_id
  );

-- Seed admin user (password: Admin@123 — MUST be changed on first login in production)
INSERT INTO customer (first_name, last_name, email, password, email_verified)
VALUES ('Admin', 'System', 'admin@ecommerce.com',
        '$2a$10$hjFXDUhzh9pIoSbIUnErq.Oa8VDkoHF2bsT8Ejdlc4Rr2fo5R6g.K',
        TRUE);

-- Assign both ADMIN and CUSTOMER roles to the seed admin
INSERT INTO customer_role (customer_id, role_id)
SELECT c.customer_id, r.role_id
FROM customer c, role r
WHERE c.email = 'admin@ecommerce.com'
  AND r.name IN ('ADMIN', 'CUSTOMER');
