create table customers(
	customer_id int generated by default as identity,
	first_name varchar(100),
	last_name varchar(100),
	email varchar(100),
	password varchar(100),
	address varchar(100),
	phone_number varchar(100),
	
	primary key (customer_id)
);

create table shipment(
	shipment_id int generated by default as identity,
	shipment_date timestamp,
	address varchar(100),
	city varchar(100),
	state varchar(20),
	country varchar(50),
	zip_code varchar(10),
	customer_id int,
	
	primary key(shipment_id)
	
);

create table "order"(
	order_id int generated by default as identity,
	order_date timestamp,
	total_price numeric(10,2),
	customer_id int,
	payment_id int,
	shipment_id int,
	
	primary key(order_id)
);

create table payment (
	payment_id int generated by default as identity,
	payment_date timestamp,
	payment_method varchar(100),
	amount numeric(10,2),
	customer_id int,
	
	primary key(payment_id)
);

create table order_item(
	order_item_id int generated by default as identity,
	quantity int,
	price numeric(10,2),
	product_id int,
	order_id int,
	
	primary key (order_item_id, order_id)
);

create table product(
	product_id int generated by default as identity,
	SKU varchar(100),
	description varchar,
	price numeric(10,2),
	stock int,
	category_id int,
	
	primary key (product_id)
);

create table category(
	category_id int generated by default as identity,
	name varchar (100),
	
	primary key (category_id)
);

alter table shipment add constraint fk_shipment_customers foreign key (customer_id) references customers(customer_id) on delete CASCADE;
alter table "order" add constraint fk_order_customers foreign key (customer_id) references customers(customer_id) on delete CASCADE;
alter table "order" add constraint fk_order_payment foreign key (payment_id) references payment(payment_id) on delete CASCADE;
alter table "order" add constraint fk_order_shipment foreign key (shipment_id) references shipment(shipment_id) on delete CASCADE;
alter table payment add constraint fk_payment_customers foreign key (customer_id) references customers(customer_id) on delete CASCADE;
alter table order_item add constraint fk_order_item_product foreign key (product_id) references product(product_id) on delete CASCADE;
alter table order_item add constraint fk_order_item_order foreign key (order_id) references "order"(order_id) on delete CASCADE;
alter table product add constraint fk_product_category foreign key (category_id) references category(category_id) on delete CASCADE;